kind: Pod
apiVersion: v1
metadata:
  name: storage-pod
spec:
  containers:
    - name: storage-pod
      image: nginx
      volumeMounts:
      - mountPath: "/data"
        name: storage-csi-volume

  volumes:
    - name: storage-csi-volume
      persistentVolumeClaim:
        claimName: storage-pvc