apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: simple-web-server # Название Pod
  labels: # Метки в формате key: value
    web: simple
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: simple-web-server # Название контейнера
    image: avasiliev/web:1.0 # Образ из которого создается контейнер
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: init-web
    image: busybox:1.32
    volumeMounts:
    - name: app
      mountPath: /app
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']    
  volumes:
  - name: app
    emptyDir: {}